version: '3'

services:
  # MySQL
  db:
    image: mysql:5.7
    container_name: mysql_host
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
     - "3307:3306"

  # postfixadmin
  postfix:
    build: ./mail
    ports:
     - "25:25"
     - "587:587"
    environment:
      TZ: 'Asia/Tokyo'
      # maildomain: 'demo.example.com'
      maildomain: 'localhost'
      # mydomain: localhost
      smtp_user: 'test:test'
      # このあたり反映されてないかも
      relayhost: '127.0.0.1:1025'
      luser_relay: maildev
    restart: always

  # maildev
  maildev:
    image: djfarrelly/maildev:latest
    ports:
     - "1080:80"
     - "1025:25"

  # nginx
  nginx:
    build: ./nginx
    ports:
     - "1081:80"
    volumes:
      - ./nginx/public:/var/www/html
  # ap
  ap:
    build: ./demo
    depends_on:
      - postfix
    ports:
      - "8081:8080"
