version: '3'

services:
  # MySQL
  db:
    image: mysql:5.7
    container_name: mysql_host
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3307:3306

  # postfixadmin
  postfix:
    image: catatnight/postfix:latest
    ports:
    - 25:25
    - 587:587
    environment:
      TZ: 'Asia/Tokyo'
      maildomain: 'demo.example.com'
      smtp_user: 'test:test'
    volumes:
    - ./mail/logs:/var/log/postfix
    restart: always

  # maildev
  maildev:
    image: djfarrelly/maildev:latest
    ports:
    - 1080:80
    - 1025:25

