# Spring Core
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/testdb
    username: test
    password: test

  # mail
  mail:
    host: 127.0.0.1
    # host: localhost
    port: 25
    # port: 587
    username: test
    password: test
    properties:
      mail:
        debug: true

  # thymeleaf
  # これ試しに入れてみる
  thymeleaf:
    check-template-location: false

# Spring Security
security:
  basic:
    enabled: false

# Doma2 Reference URL <https://github.com/domaframework/doma-spring-boot>
doma:
  dialect: mysql
  sql-file-repository: no_cache

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          EnumType: trace
          descriptor:
            sql:
              BasicBinder: trace
